# Generated by Django 4.2.4 on 2024-01-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_type_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caveman',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.type'),
        ),
    ]
