# Generated by Django 4.2.4 on 2024-01-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_alter_caveman_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
    ]
