# Generated by Django 4.2.4 on 2023-10-23 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
